### PR TITLE
Task-4

### PR DESCRIPTION
**Pull request by vusatui**
[Swagger documentation](https://qio6nagzs3.execute-api.eu-west-1.amazonaws.com/swagger-ui)
[Front-end PR link](https://github.com/vusatui/shop-vue-vuex-cloudfront/pull/3)
1. Created 'Postgres' instance;
2. Created initial structure of products db;
3. Added list of products;
4. Added sql-script file;
5. Added 'pg' module;
6. Refactored endpoint for using with db;
7. Added 'createProduct' endpoint;
8. Added  product validation before create that returns 400;
9. Added global error handler that returns 500 status code;
10. Added logging;
11. Creating of new product running within transaction;

Screenshot 2022-07-31 at 21 14 12

### CODE REVIEW

**Comment by escoemi** [comment]
Hi Anton, good job, next time it would be nice if you can specify what was done, but from the evaluation criteria.

I've tested your lambdas and looked at your code, so far the only point missing it seems to be 

5 - Your own Frontend application is integrated with Product Service (/products API) and products from Product Service are represented on Frontend. Link to a working Frontend application is provided for cross-check reviewer.

I've looked at https://d32kvoiexx06pv.cloudfront.net/ (that i found on the code) and it doesn't trigger any successful call, it seems it still working with mock data. Hence current score 8

**Comment by vusatui** [comment]
@escoemi 
I have just finished the work. Could you check again please?

**Comment by escoemi** [comment]
Hi Anton, i've review https://d32kvoiexx06pv.cloudfront.net/ but it seems it's still not triggering any call to /products get API.

image

**Comment by vusatui** [comment]
@escoemi - **GET products** evaluates at this page [https://d32kvoiexx06pv.cloudfront.net/admin/products](https://d32kvoiexx06pv.cloudfront.net/admin/products)

**Pull request merged**
